version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: portfolio-docker
        working_dir: /srv/app
        command: ng serve --open
        volumes:
            - .:/srv/app
        ports:
            - 5001:5000
